import type { Metadata } from "next";
import "./globals.css";
import MantineProviderRegistry from "./mantine";
import { Shell } from "@lal-erp/core";
import { LocaleProvider } from "./locale-provider";
import { theme } from "@lal-erp/theme/mantine";
import { MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LocaleProvider>
          {/* <MantineProviderRegistry>
            <Shell>{children}</Shell>
          </MantineProviderRegistry>{" "} */}
          <MantineProvider>
            <Shell>{children}</Shell>
          </MantineProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
